>room_command smash core~
if roomvalue($1) & 1
	echoat $n 你目前無法在這裡做這項動作。
	break
endif
if rmobcount(8110) > 0
	echoat $n 由於 雙頭龍(secundus) 距離 黑核晶(black crystal of core) 太近，因而你無法下手....
	break
endif
if rmobcount(8112) > 0
	modrvt v1 | 1
	if roomvalue($0) == 0
		echoat $n 你使用手上的武器重擊 黑核晶(black crystal of core) ....
		echoaround $n $n 使用手上的武器重擊 黑核晶(black crystal of core) ....
		if str($n) < 20
			callout 1 echoat $n 但是你的力量過小，無法對 黑核晶(black crystal of core) 造成損傷....
			callout 1 echoaround $n $n 似乎力量過小，無法對 黑核晶(black crystal of core) 造成損傷....
		else
			callout 1 echoat $n 你的重擊讓 黑核晶(black crystal of core) 受到輕微損傷....
			callout 1 echoaround $n $n 的重擊讓 黑核晶(black crystal of core) 受到輕微損傷....
			callout 1 modrvt v0 = 1
		endif
		callout 2 modrvt v1 r 1
		break
	endif
	if roomvalue($0) == 1
		echoat $n 你使用手上的武器重擊 黑核晶(black crystal of core) ....
		echoaround $n $n 使用手上的武器重擊 黑核晶(black crystal of core) ....
		if str($n) < 20
			callout 1 echoat $n 但是你的力量過小，無法對 黑核晶(black crystal of core) 造成損傷....
			callout 1 echoaround $n $n 似乎力量過小，無法對 黑核晶(black crystal of core) 造成損傷....
		else
			callout 1 echoat $n 你的重擊讓 黑核晶(black crystal of core) 受到一些損傷....
			callout 1 echoaround $n $n 的重擊讓 黑核晶(black crystal of core) 受到一些損傷....
			callout 1 modrvt v0 = 2
		endif
		callout 2 modrvt v1 r 1
		break
	endif
	if roomvalue($0) == 2
		echoat $n 你使用手上的武器重擊 黑核晶(black crystal of core) ....
		echoaround $n $n 使用手上的武器重擊 黑核晶(black crystal of core) ....
		if str($n) < 20
			callout 1 echoat $n 但是你的力量過小，無法對 黑核晶(black crystal of core) 造成損傷....
			callout 1 echoaround $n $n 似乎力量過小，無法對 黑核晶(black crystal of core) 造成損傷....
		else
			callout 1 echoat $n 你的重擊讓 黑核晶(black crystal of core) 受到普通損傷....
			callout 1 echoaround $n $n 的重擊讓 黑核晶(black crystal of core) 受到普通損傷....
			callout 1 modrvt v0 = 3
		endif
		callout 2 modrvt v1 r 1
		break
	endif
	if roomvalue($0) == 3
		echoat $n 你使用手上的武器重擊 黑核晶(black crystal of core) ....
		echoaround $n $n 使用手上的武器重擊 黑核晶(black crystal of core) ....
		if str($n) < 20
			callout 1 echoat $n 但是你的力量過小，無法對 黑核晶(black crystal of core) 造成損傷....
			callout 1 echoaround $n $n 似乎力量過小，無法對 黑核晶(black crystal of core) 造成損傷....
		else
			callout 1 echoat $n 你的重擊讓 黑核晶(black crystal of core) 受到嚴重損傷....
			callout 1 echoaround $n $n 的重擊讓 黑核晶(black crystal of core) 受到嚴重損傷....
			callout 1 modrvt v0 = 4
		endif
		callout 2 modrvt v1 r 1
		break
	endif
	if roomvalue($0) == 4
		echoat $n 你使用手上的武器重擊 黑核晶(black crystal of core) ....
		echoaround $n $n 使用手上的武器重擊 黑核晶(black crystal of core) ....
		if str($n) < 20
			callout 1 echoat $n 但是你的力量過小，無法對 黑核晶(black crystal of core) 造成損傷....
			callout 1 echoaround $n $n 似乎力量過小，無法對 黑核晶(black crystal of core) 造成損傷....
		else
			callout 1 echoat $n 你的重擊讓 黑核晶(black crystal of core) 受到毀滅性損傷....
			callout 1 echoaround $n $n 的重擊讓 黑核晶(black crystal of core) 受到毀滅性損傷....
			callout 1 modrvt v0 = 5
		endif
		callout 2 modrvt v1 r 1
		break
	endif
	if roomvalue($0) == 5
		echoat $n 你使用手上的武器重擊 黑核晶(black crystal of core) ....
		echoaround $n $n 使用手上的武器重擊 黑核晶(black crystal of core) ....
		if str($n) < 20
			callout 1 echoat $n 但是你的力量過小，無法對 黑核晶(black crystal of core) 造成損傷....
			callout 1 echoaround $n $n 似乎力量過小，無法對 黑核晶(black crystal of core) 造成損傷....
		else
			callout 1 echoat $n 你的重擊摧毀了 黑核晶(black crystal of core)....
			callout 1 echoaround $n $n 的重擊摧毀了 黑核晶(black crystal of core)....
			callout 1 purge core-nirvana
			callout 1 modrvt v0 = 0
			callout 1 modrvt t0 = 150
		endif
		callout 2 modrvt v1 r 1
		callout 2 rcall nirvana_core $n
	endif
else
	echoat $n 這裡並沒有這項東西。
endif
~
>room_defun nirvana_core~
if mobcount(8112) == 0
	echotoall 舊大陸的天空傳來陣陣的閃電，通往涅盤大地的結界被 $N 開啟了....
	echoat $n 通往涅盤大地的結界被你開啟了....
	echoaround $n 通往涅盤大地的結界被 $N 開啟了....
force 8122 makedoor 0 結界已經完全消失了 field 0 0 8121
	force 8121 makedoor 2 結界已經完全消失了 field 0 0 8122
	force 8124 makedoor 0 結界已經完全消失了 field 0 0 8125
	force 8125 makedoor 2 結界已經完全消失了 field 0 0 8124
	if is_qmark($n) == thoran_master_quest 100006
		mod_qmark $n thoran_master_quest v0 = 7
		if mobcount(26526) > 0
			force 26532 purge dragon-thoran
			force 5 mload 26526
		else
			force 5 mload 26526
		endif
		if mobcount(26554) > 0
		else
			force 26532 mload 26554
		endif
		callout 1 echoat $n 你似乎可以感受到涅盤大地對星光之城的詛咒魔力似乎消失了....
	endif
endif
~
|