[area]
name = "安提珥墓穴"
identity = "grave"
builders = "YH"
translator = "----"
modifier = "----"
vnum_start = 3600
vnum_end = 3699
security = 1
recall = 3001
f_toggle = false

[objects.3600]
keywords = "舊eq 無法使用的vnum"
short_description = "舊eq 無法使用的vnum"
long_description = "-  舊eq 無法使用的vnum"
action_description = ""
item_type = "TRASH"
extra_flags = []
wear_flags = []
values = ["0", "0", "0", "0"]
weight = 0
cost = 0
level_limited = 0

[objects.3601]
keywords = "舊eq 無法使用的vnum"
short_description = "舊eq 無法使用的vnum"
long_description = "-  舊eq 無法使用的vnum"
action_description = ""
item_type = "TRASH"
extra_flags = []
wear_flags = []
values = ["0", "0", "0", "0"]
weight = 0
cost = 0
level_limited = 0

[objects.3602]
keywords = "舊eq 無法使用的vnum"
short_description = "舊eq 無法使用的vnum"
long_description = "-  舊eq 無法使用的vnum"
action_description = ""
item_type = "TRASH"
extra_flags = []
wear_flags = []
values = ["0", "0", "0", "0"]
weight = 0
cost = 0
level_limited = 0

[objects.3603]
keywords = "舊eq 無法使用的vnum"
short_description = "舊eq 無法使用的vnum"
long_description = "-  舊eq 無法使用的vnum"
action_description = ""
item_type = "TRASH"
extra_flags = []
wear_flags = []
values = ["0", "0", "0", "0"]
weight = 0
cost = 0
level_limited = 0

[objects.3604]
keywords = "舊eq 無法使用的vnum"
short_description = "舊eq 無法使用的vnum"
long_description = "-  舊eq 無法使用的vnum"
action_description = ""
item_type = "TRASH"
extra_flags = []
wear_flags = []
values = ["0", "0", "0", "0"]
weight = 0
cost = 0
level_limited = 0

[objects.3605]
keywords = "舊eq 無法使用的vnum"
short_description = "舊eq 無法使用的vnum"
long_description = "-  舊eq 無法使用的vnum"
action_description = ""
item_type = "TRASH"
extra_flags = []
wear_flags = []
values = ["0", "0", "0", "0"]
weight = 0
cost = 0
level_limited = 0

[objects.3610]
keywords = "舊eq 無法使用的vnum"
short_description = "舊eq 無法使用的vnum"
long_description = "-  舊eq 無法使用的vnum"
action_description = ""
item_type = "TRASH"
extra_flags = []
wear_flags = []
values = ["0", "0", "0", "0"]
weight = 0
cost = 0
level_limited = 0

[objects.3611]
keywords = "舊eq 無法使用的vnum"
short_description = "舊eq 無法使用的vnum"
long_description = "-  舊eq 無法使用的vnum"
action_description = ""
item_type = "TRASH"
extra_flags = []
wear_flags = []
values = ["0", "0", "0", "0"]
weight = 0
cost = 0
level_limited = 0

[objects.3612]
keywords = "舊eq 無法使用的vnum"
short_description = "舊eq 無法使用的vnum"
long_description = "-  舊eq 無法使用的vnum"
action_description = ""
item_type = "TRASH"
extra_flags = []
wear_flags = []
values = ["0", "0", "0", "0"]
weight = 0
cost = 0
level_limited = 0

[objects.3613]
keywords = "舊eq 無法使用的vnum"
short_description = "舊eq 無法使用的vnum"
long_description = "-  舊eq 無法使用的vnum"
action_description = ""
item_type = "TRASH"
extra_flags = []
wear_flags = []
values = ["0", "0", "0", "0"]
weight = 0
cost = 0
level_limited = 0

[rooms.3600]
name = "buff room"
description = """
buffer room of Antior grave
"""
flags = ["NO_MOB"]
sector = "INSIDE"
