[area]
name = "{36 42} 巫妖之塔"
identity = "lich"
builders = "Ryzen"
translator = "Feena"
modifier = ""
vnum_start = 29350
vnum_end = 29399
security = 1
recall = 4580
death = 401
f_toggle = false

[mobiles.29350]
keywords = "Death Knight"
short_description = "死亡騎士(Death Knight)"
long_description = "一名不死的骷髏騎士(knight)把守在這個房間。\n"
description = """
死亡騎士是個很強悍的敵手，是由某個強力的死靈師所召喚而來的，它們在過去
的全盛時期可是最有名望的騎士們。
"""
act_flags = []
affected_flags = []
alignment = 0
level = 0
mod_hitplus = 0
mod_mana = -750
mod_hitroll = 0
mod_damroll = 0
mod_ac = 15
mod_svs = 0
dodge = 1850
mod_pp = 5
gold = 0
sex = "neutral"

[objects.29350]
keywords = "black mace "
short_description = "古老黑色鎚子(old black mace)"
long_description = "一把古老的黑色鐵鎚(mace)被安置在這裡。"
action_description = "iron"
item_type = "TRASH"
extra_flags = []
wear_flags = []
values = ["mace 6 7 pound 0\n40 25 1000 P\n#29351\nglowing skull", "燃燒的頭骨(flaming Skull)", "一顆人類的頭骨(skull)飄浮在這裡，在青藍色的火燄中輪廓分明。", "stone"]
weight = 0
cost = 0
level_limited = 0
