[area]
name = "議會"
identity = "redferne"
builders = "Diku"
translator = "Pluto"
modifier = "YH"
vnum_start = 7900
vnum_end = 7918
security = 1
recall = 3001
f_toggle = true

[mobiles.7900]
keywords = "Comitia knight"
short_description = "議院騎士(Knight of Comitia)"
long_description = "議院騎士(Knight of Comitia)在此守衛著大門。\n"
description = """
他全身穿著銀白色的護甲，看起來非常的強大。這個騎士站在這裡守衛著大門，
隨時作好應戰的準備。
"""
act_flags = ["NPC", "SENTINEL", "STAY_AREA"]
affected_flags = ["DETECT_INVIS", "DETECT_HIDDEN", "HOLD"]
alignment = 1000
level = 26
mod_hitplus = 500
mod_mana = 0
mod_hitroll = 0
mod_damroll = 0
mod_ac = 0
mod_svs = 0
dodge = 0
mod_pp = 0
gold = 1000
sex = "male"
class = ["WARRIOR", "MAGE"]
special_function = "spec_cast_cleric"
[[mobiles.7900.programs]]
trigger = "repop_prog"
argument = "100"
script = """
mpoload 7900 20
mpoload 7901 20
mpoload 7902 20
mpoload 7903 20
mpoload 7904 20
mpoload 7905 20
mpoload 7906 20
mpoload 7907 20
mpoload 7908 20
mpat 5 wear all
"""

[mobiles.7901]
keywords = "Comitia grand knight"
short_description = "議院大騎士(Grand Knight of Comitia)"
long_description = "議院大騎士(Grand Knight of Comitia)在此等候需要協助的人的造訪。\n"
description = """
他全身穿著銀白色的護甲，看起來非常的強大。這個騎士站在這裡對你微笑，
站在這邊準備幫助一些心靈純潔、需要協助的人們。
"""
act_flags = ["NPC", "SENTINEL", "STAY_AREA"]
affected_flags = ["DETECT_INVIS", "DETECT_HIDDEN", "HOLD"]
alignment = 1000
level = 65
mod_hitplus = 50000
mod_mana = 0
mod_hitroll = 0
mod_damroll = 0
mod_ac = 0
mod_svs = 0
dodge = 0
mod_pp = 0
gold = 1000
sex = "male"
class = ["WARRIOR", "MAGE"]

[objects.7900]
keywords = "plate breast silvery"
short_description = "銀白胸甲(silvery breast plate)"
long_description = "一件銀色的盔甲(silvery breast plate)掉在地上."
action_description = ""
item_type = "ARMOR"
extra_flags = ["MAGIC", "BLESS", "ANTI_EVIL", "ANTI_NEUTRAL"]
wear_flags = ["TAKE", "WEAR_BODY"]
values = ["0", "0", "225", "0"]
weight = 40
cost = 25000
level_limited = 35
material = "silver"
[[objects.7900.extra_descriptions]]
keywords = "plate breast silvery"
description = """
在胸甲上你看到一個巨大的玫瑰浮雕，材質看起來像是銀或是白金。
"""
[[objects.7900.applies]]
type = "STR"
value = 3

[objects.7901]
keywords = "plates leg silvery"
short_description = "銀白脛甲(silvery leg plates)"
long_description = "一雙銀色脛甲(silvery leg plates)掉在地上."
action_description = ""
item_type = "ARMOR"
extra_flags = ["MAGIC", "BLESS", "ANTI_EVIL", "ANTI_NEUTRAL"]
wear_flags = ["TAKE", "WEAR_LEGS"]
values = ["0", "0", "225", "0"]
weight = 20
cost = 12500
level_limited = 35
material = "silver"
[[objects.7901.extra_descriptions]]
keywords = "leg plates silvery"
description = """
這雙脛甲看起來像是銀或是白金做的，你可以看到它的外側有一朵玫瑰。
"""
[[objects.7901.applies]]
type = "INT"
value = 3

[objects.7902]
keywords = "gloves silvery"
short_description = "銀白護手(silvery gloves)"
long_description = "一雙銀色護手(silvery gloves)掉在地上."
action_description = ""
item_type = "ARMOR"
extra_flags = ["MAGIC", "BLESS", "ANTI_EVIL", "ANTI_NEUTRAL"]
wear_flags = ["TAKE", "WEAR_HANDS"]
values = ["0", "0", "225", "0"]
weight = 14
cost = 900
level_limited = 35
material = "silver"
[[objects.7902.extra_descriptions]]
keywords = "gloves silvery"
description = """
這個手套是由銀線織成的。
"""
[[objects.7902.applies]]
type = "HITROLL"
value = 3

[objects.7903]
keywords = "helmet silvery"
short_description = "銀白頭盔(silvery helmet)"
long_description = "一頂銀色頭盔(silvery helmet)被擺在地上."
action_description = ""
item_type = "ARMOR"
extra_flags = ["MAGIC", "BLESS", "ANTI_EVIL", "ANTI_NEUTRAL"]
wear_flags = ["TAKE", "WEAR_HEAD"]
values = ["0", "0", "225", "0"]
weight = 35
cost = 9000
level_limited = 35
material = "silver"
[[objects.7903.extra_descriptions]]
keywords = "helmet silvery"
description = """
這頂頭盔是由白金或銀織成的，上面來有一撮白色的毛繫在上面。
"""
[[objects.7903.applies]]
type = "WIS"
value = 3

[objects.7904]
keywords = "shield rose"
short_description = "玫瑰之盾(rose shield)"
long_description = "一面鑲有玫瑰(rose)紋飾的盾(shield)."
action_description = ""
item_type = "ARMOR"
extra_flags = ["MAGIC", "BLESS", "ANTI_EVIL", "ANTI_NEUTRAL"]
wear_flags = ["TAKE", "WEAR_SHIELD"]
values = ["0", "0", "225", "0"]
weight = 20
cost = 15000
level_limited = 0
material = "silver"
[[objects.7904.extra_descriptions]]
keywords = "rose shield"
description = """
你可以看到白色表面上有一個清楚亮麗的玫瑰紋飾。
"""
[[objects.7904.applies]]
type = "AC"
value = -30

[objects.7905]
keywords = "boots silvery"
short_description = "銀白長靴(silvery boots)"
long_description = "一雙銀色長靴(silvery boots)被擺在地上."
action_description = ""
item_type = "ARMOR"
extra_flags = ["MAGIC", "BLESS", "ANTI_EVIL", "ANTI_NEUTRAL"]
wear_flags = ["TAKE", "WEAR_FEET"]
values = ["0", "0", "225", "0"]
weight = 40
cost = 2000
level_limited = 35
material = "silver"
[[objects.7905.extra_descriptions]]
keywords = "boots silvery"
description = """
這雙靴子是由銀做成的。
"""
[[objects.7905.applies]]
type = "DEX"
value = 3

[objects.7906]
keywords = "plates arm silvery"
short_description = "銀白臂甲(silvery arm plates)"
long_description = "一對銀色臂甲(silvery arm plates)掉在地上."
action_description = ""
item_type = "ARMOR"
extra_flags = ["MAGIC", "BLESS", "ANTI_EVIL", "ANTI_NEUTRAL"]
wear_flags = ["TAKE", "WEAR_ARMS"]
values = ["0", "0", "225", "0"]
weight = 40
cost = 12500
level_limited = 35
material = "silver"
[[objects.7906.extra_descriptions]]
keywords = "plates arm silvery"
description = """
這對臂甲看起來像是銀或是白金做的，你可以看到它的外側有一朵玫瑰。
"""
[[objects.7906.applies]]
type = "CON"
value = 3

[objects.7907]
keywords = "cloak white"
short_description = "白絲披風(white cloak)"
long_description = "一襲由白絲線縫合而成的披風(white cloak)."
action_description = ""
item_type = "ARMOR"
extra_flags = ["MAGIC", "BLESS", "ANTI_EVIL", "ANTI_NEUTRAL"]
wear_flags = ["TAKE", "WEAR_ABOUT"]
values = ["0", "0", "225", "0"]
weight = 10
cost = 10000
level_limited = 0
material = "silk"
[[objects.7907.extra_descriptions]]
keywords = "cloak white"
description = """
這是一件手工很細，但是卻不知道材質是什麼，外表呈現出明亮的白色。
"""
[[objects.7907.applies]]
type = "STR"
value = 1
[[objects.7907.applies]]
type = "WIS"
value = 2

[objects.7908]
keywords = "silvery rapier"
short_description = "銀白刺劍(silvery rapier)"
long_description = "一柄銀色的刺劍(rapier)掉在地上."
action_description = ""
item_type = "WEAPON"
extra_flags = ["MAGIC"]
wear_flags = ["TAKE", "WIELD"]
values = ["100", "0", "0", "3"]
weight = 5
cost = 1000
level_limited = 36
level = 15
material = "silver"
[[objects.7908.extra_descriptions]]
keywords = "silvery rapier"
description = """
這柄輕巧細長的刺劍看起來像是銀或是白金做的，你可以看到它的外側有一朵玫瑰。
"""
[[objects.7908.applies]]
type = "DEX"
value = 2
[[objects.7908.applies]]
type = "HITROLL"
value = 15
[[objects.7908.applies]]
type = "APPLY_ADAMAGE"
value = 50

[objects.7909]
keywords = "treasure coins"
short_description = "大量的財寶(huge treasure)"
long_description = "大量的財寶(treasure)散落在這邊，看起來非常具有價值。"
action_description = ""
item_type = "MONEY"
extra_flags = []
wear_flags = ["TAKE"]
values = ["23000", "0", "0", "0"]
weight = 0
cost = 0
level_limited = 0
material = "gold"
[[objects.7909.extra_descriptions]]
keywords = "treasure"
description = """
看起來就知道裡面的錢非常的多。
"""

[objects.7910]
keywords = "chest"
short_description = "木製箱子(wooden chest)"
long_description = "一個木製箱子(wooden chest)被放在角落。"
action_description = ""
item_type = "CONTAINER"
extra_flags = []
wear_flags = ["TAKE"]
values = ["200", "15", "7911", "0"]
weight = 300
cost = 0
level_limited = 0
material = "wooden"
[[objects.7910.extra_descriptions]]
keywords = "chest"
description = """
一個型式簡單的木箱，附了一個黃銅鎖。
"""

[objects.7911]
keywords = "key"
short_description = "黃銅鑰匙(small brass key)"
long_description = "一把小小的黃銅鑰匙(brass key)放在這邊。"
action_description = ""
item_type = "KEY"
extra_flags = []
wear_flags = ["TAKE"]
values = ["7910", "0", "0", "0"]
weight = 1
cost = 0
level_limited = 0
material = "brass"
[[objects.7911.extra_descriptions]]
keywords = "key"
description = """
一把小的簡單黃銅鑰匙。
"""

[rooms.7900]
name = "議會大樓外"
description = """
你來到一個位於高處的寬廣平臺。剛進入時，瞬間襲來一陣風壓讓眼睛睜不開來。
稍微適應後，發現風在這裡幾乎是完全靜止，且陽光十分的溫暖柔和。平臺下緣的高度
剛好跟雲層切齊，這裡位於的高度足夠俯瞰整座史卡拉貝城。在南方有片看起來詭異的
雲朵，北方則有棟雄偉壯觀的建築 － 史卡拉貝議會大樓。
"""
flags = ["NO_MOB", "UNDERGROUND"]
sector = "INSIDE"
[rooms.7900.exits.down]
description = "從樓梯滾下去能回到地面。\n"
keywords = ""
locks = []
key = -1
to_room = 7916
[rooms.7900.exits.north]
description = "巨大的大門連接著一棟雄偉壯觀的建築。\n"
keywords = "巨大的大門"
locks = ["ISDOOR", "CLOSED", "LOCKED", "BASHPROOF", "PICKPROOF", "PASSPROOF"]
key = -1
to_room = 7901
[rooms.7900.exits.south]
description = "南邊有些看起來詭異的雲朵。\n"
keywords = ""
locks = []
key = 0
to_room = 9101
[[rooms.7900.resets.mobiles]]
vnum = 7900
limit = 1

[rooms.7901]
name = "大廳的東南方盡頭"
description = """
你站在一個非常寬廣但是微暗的巨大大廳上，雖然這邊有點陰暗，但是你卻
無法知道照明是由那邊提供的。牆壁上似乎發散著給予所有造訪者溫暖而且令人
愉快的感覺。一幅巨大的畫掛在其中一面牆壁上。一個巨型的樓梯往上通往塔中
。在你的東邊有個巨大的通道帶領你離開大廳。這裡有個高大的橡木門。這個雄
偉的大廳由北方延伸至此。在你的南邊你看到一扇巨大、笨重的鐵門。這扇門似
乎是唯一可以離開這個雄偉城堡的出口。在你的西邊你看到一扇巨大的灰色門。
"""
flags = ["NO_TELEPORT_IN"]
sector = "INSIDE"
[[rooms.7901.extra_descriptions]]
keywords = "letters"
description = """
They read "LIBRARY".
"""
[[rooms.7901.extra_descriptions]]
keywords = "runes"
description = """
These runes are utterly strange to you, but you are in luck today: Under
the runes you can just make out a sentence in Common. It goes : " Stay out,
if you treasure your life. That is if you are mortal.".
"""
[rooms.7901.exits.east]
description = "You see there a tall oak door. It looks quite tightly closed to you.\nOn it little runes are chiselled into the wood.\n"
keywords = "oak tall east oakdoor talldoor eastdoor"
locks = ["ISDOOR", "CLOSED", "PICKPROOF"]
key = -1
to_room = 7910
[rooms.7901.exits.north]
description = "The hallway continues that way. You can see more doorways under the\nwooden staircase in that direction.\n"
keywords = ""
locks = []
key = -1
to_room = 7904
[rooms.7901.exits.south]
description = "Here you see a REAL door. It would be more proper to call this a\n\"GATE\", rather than a \"door\". It's really HUGE! On it hangs a large\nsign with very large letters spelling : \"EMERGENCY EXIT\".\n"
keywords = "gate"
locks = ["ISDOOR", "CLOSED", "PICKPROOF"]
key = -1
to_room = 7900
[rooms.7901.exits.up]
description = "You see the staircase extending upwards into the very high tower.\nIt ends in what seems like a large bedroom up there.\n"
keywords = ""
locks = []
key = -1
to_room = 7909
[rooms.7901.exits.west]
description = "This looks like a \"door\" in the meaning of the word. The ashen wood\nis painted in a peculiar yellow colour. Small letters are written\nwith black on it.\n"
keywords = "ashen ash door west yellow"
locks = ["ISDOOR", "CLOSED", "PICKPROOF"]
key = -1
to_room = 7902

[rooms.7902]
name = "瑞芬的圖書館"
description = """
這裡真的是一個資訊十分豐富的地方！書本與捲軸擺滿了整個書架。在西北
邊角落的一個房間中，一個星球儀(globe worlds)上面畫著整個史卡拉貝大陸的
地圖(maps)。兩個巨大、十分舒適的椅子以及一面橡木材質、裝飾華麗的桌子擺
在圖書館的中間。這裡的照明都是由掛在天花板上距離地面約10英尺的華麗燭台
所提供。在東邊有一扇巨大的灰色門。一面巨大的玻璃窗嵌在西邊的牆壁上。
"""
flags = ["NO_TELEPORT_IN"]
sector = "INSIDE"
[[rooms.7902.extra_descriptions]]
keywords = "river"
description = """
You see a large and winding river cut through the landscape, starting at an
enormous inland lake, it seeps through Skarabrae and finally ends up in the
Grand Sea on the West-coast of the land.
"""
[[rooms.7902.extra_descriptions]]
keywords = "out outside beyond"
description = """
The clouds muster and form the ground on which this entire building is set.
Through the thinnest of the clouds you can just make out MIDGAARD with all
it's magnificent activity.
"""
[[rooms.7902.extra_descriptions]]
keywords = "window glass"
description = """
These windows are really BIG! They reach from about 20 inches above the
floor to approximately 10 inches under the ceiling. If you try and
"look out", you might see what might lie beyond these windows.
"""
[[rooms.7902.extra_descriptions]]
keywords = "chairs leather arm-chairs"
description = """
These two chair are exactly alike one another. They look incredibly
comfortable. They're both made from old leather, and yet they seem so worn
that they can be nothing but a perfect place for a long needed rest.
"""
[[rooms.7902.extra_descriptions]]
keywords = "skarabrae town city"
description = """
You see a small speck with woods on the west from it, plains to the east
from it and mountains to the north from it. To the south from it you can
see a thin trail lead to a large castle. Finally you notice a rather large
river pour in from the east and go through Skarabrae in the middle.
"""
[[rooms.7902.extra_descriptions]]
keywords = "globe worlds map"
description = """
你看到一幅巨大的世界地圖在這個星球儀上。裡面詳細到連所有小鎮的位置都被
標了出來。在整個地圖的中間，你看到一個面積最大的城鎮 － 史卡拉貝(Skarabrae)
上面更標示著所有山丘、森林、平原、海洋的位置。
"""
[rooms.7902.exits.east]
description = "You can see an old ashen door, painted in a peculiar yellow colour.\n"
keywords = "door ash ashen east"
locks = ["ISDOOR", "CLOSED", "PICKPROOF"]
key = -1
to_room = 7901

[rooms.7903]
name = "納里之樓的魔力空間"
description = """
這裡是一間黑暗、沈悶的房間，只有牆上一個昏暗的蠟燭在提供照明。一捆
看起來蠻有趣的物品在房間的中間。這邊沒有把任何的家具。唯一的出口經由一
扇低矮的鐵門指向西邊。
"""
flags = ["NO_TELEPORT_IN"]
sector = "INSIDE"
[rooms.7903.exits.west]
description = "You see only the back of a safe's steel door.\n"
keywords = ""
locks = []
key = -1
to_room = 0

[rooms.7904]
name = "大廳的北邊盡頭"
description = """
你站在巨大大廳的北邊盡頭。這裡由於正好在巨大的木製樓梯的下面，因此
這邊照明似乎稍嫌不足，但是還不會影響你的視線。在你的北邊是一間廚房。南
邊則是大廳的南方盡頭。在東邊有一扇金屬門。西邊有一扇巨大的白楊木門。
"""
flags = ["NO_TELEPORT_IN"]
sector = "INSIDE"
[rooms.7904.exits.east]
description = "You see a huge metal door. From it a foul stench emanates. The smell is the\nmost awful experience in your entire life. A thought seeps through this\nterrible stench and into your mind : \"Monsters\", you feel BAD about opening\nthat door.\n"
keywords = "steel metal huge"
locks = ["ISDOOR", "CLOSED", "PICKPROOF"]
key = -1
to_room = 7913
[rooms.7904.exits.north]
description = ""
keywords = ""
locks = []
key = -1
to_room = 7906
[rooms.7904.exits.south]
description = "The rest of the hall lies in that direction, and so does the exit.\n"
keywords = ""
locks = []
key = -1
to_room = 7901
[rooms.7904.exits.west]
description = "The door has \"SITTING ROOM\" written on it. It is made from Aspenwood and\nis beautifully carven with small elves as main issue of sculpture.\n"
keywords = "aspen asp"
locks = ["ISDOOR", "CLOSED", "PICKPROOF"]
key = -1
to_room = 7905

[rooms.7905]
name = "納里之樓的起居室"
description = """
你站在一個十分舒適房間的中間。牆壁上有一幅畫，畫著微笑的國王與皇后當裝
飾。最引人注目的畫是一幅畫著全身穿著閃亮盔甲的王子畫像。在一面牆壁前有
一把年代十分久遠的椅子(chair)。唯一的出口指向東邊的白楊木門。
"""
flags = ["NO_TELEPORT_IN"]
sector = "INSIDE"
[[rooms.7905.extra_descriptions]]
keywords = "chair arm-chair"
description = """
這真是一個上古的精美椅子。連上頭的軟墊雕製都那麼的精美。
"""
[rooms.7905.exits.east]
description = "The door seems to be a very HEAVY door, carved completely from the trunk of\nan Aspen tree.\n"
keywords = "asp aspen door heavy"
locks = ["ISDOOR", "CLOSED", "PICKPROOF"]
key = -1
to_room = 7904

[rooms.7906]
name = "納里之樓的廚房"
description = """
這裡是這邊用來用餐的地方。你聽到某處一陣似乎是老鼠在啃食肉類與麵包
的討厭聲音。這些聲音讓你想起你現在十分的飢餓。唯一可以看到的出口指向南
邊通往大廳的北邊盡頭。在北邊是一個食物儲藏室，東邊則是有一個冷凍庫。
"""
flags = ["NO_TELEPORT_IN"]
sector = "INSIDE"
[rooms.7906.exits.east]
description = "You can see the fridge from here. In it are drinks all over.\n"
keywords = "fridge"
locks = ["ISDOOR", "CLOSED", "PICKPROOF"]
key = -1
to_room = 7908
[rooms.7906.exits.north]
description = "It's dark in there,  but the sounds from there are unmistakably from rats.\n"
keywords = "larder wooden cupboard"
locks = ["ISDOOR", "CLOSED", "PICKPROOF"]
key = -1
to_room = 7907
[rooms.7906.exits.south]
description = "You can see the northern end of the hall.\n"
keywords = ""
locks = []
key = -1
to_room = 7904

[rooms.7907]
name = "食物儲藏室"
description = """
四周都是食物。在食物堆中你竟然看到一隻巨大的老鼠在裡頭啃食著食物。
"""
flags = ["NO_TELEPORT_IN"]
sector = "INSIDE"
[rooms.7907.exits.south]
description = ""
keywords = "door wooden larder exit"
locks = ["ISDOOR", "CLOSED", "PICKPROOF"]
key = -1
to_room = 7906

[rooms.7908]
name = "冷凍庫"
description = """
這裡儲藏著飲料、飲用水與酒。
"""
flags = ["NO_TELEPORT_IN"]
sector = "INSIDE"
[rooms.7908.exits.west]
description = ""
keywords = "door exit fridge"
locks = ["ISDOOR", "CLOSED", "PICKPROOF"]
key = -1
to_room = 7906

[rooms.7909]
name = "在樓梯上"
description = """
你在此可以往上或往下觀看樓梯。這個樓梯好像無止盡一般通往上面與下面
，因為你根本看不到樓梯的盡頭。但是那只是矇騙你的幻象，你往上走了沒幾步
就可以看到上面是瑞芬的房間。往下沒幾步就通到了大廳的南邊盡頭。
"""
flags = ["NO_MOB", "INDOORS", "PRIVATE"]
sector = "INSIDE"
[rooms.7909.exits.down]
description = ""
keywords = ""
locks = []
key = -1
to_room = 7901
[rooms.7909.exits.up]
description = ""
keywords = ""
locks = []
key = -1
to_room = 7911

[rooms.7910]
name = "寶藏室"
description = """
這裡真是光輝耀眼。唯一的出口指向西邊通過橡木門。
"""
flags = ["NO_TELEPORT_IN"]
sector = "INSIDE"
[rooms.7910.exits.east]
description = ""
keywords = "safe steel"
locks = []
key = -1
to_room = 0
[rooms.7910.exits.west]
description = "You see a tall oak door.\n"
keywords = "door oak tall"
locks = ["ISDOOR", "CLOSED", "PICKPROOF"]
key = -1
to_room = 7901

[rooms.7911]
name = "瑞芬的臥室"
description = """
這裡是一間有著各種高級生活用品，同時裝飾十分羅曼蒂克的舒適房間。一
個壁爐嵌在東邊的牆上，同時裡面正燃燒著木頭讓整個房間十分的溫暖。房間中
有一個幾乎佔了房間一半面積的巨大床鋪。面積應該有300平方英尺吧，簡直不像
是「床」？一個巨大的樓梯往下通往大廳。往南經過一扇門可以到達陽台。
"""
flags = ["NO_TELEPORT_IN"]
sector = "INSIDE"
[rooms.7911.exits.down]
description = ""
keywords = ""
locks = []
key = -1
to_room = 7909
[rooms.7911.exits.south]
description = "The sun seems to shine out there, warmly and comforting.\n"
keywords = "doors"
locks = ["ISDOOR", "CLOSED"]
key = -1
to_room = 7912

[rooms.7912]
name = "空中城堡的陽台"
description = """
你在這邊可以看到整個世界的脈動、運行。一個山谷往南不斷的延伸到你眼
睛看不到的地方。在你的下方你可以看到進入這個城堡的入口。在你的北邊就是
回到瑞芬臥室的門。
"""
flags = ["NO_TELEPORT_IN"]
sector = "INSIDE"
[rooms.7912.exits.down]
description = "You see the ground on which this castle is set. Funnily it seems to you that\nit's no more than clouds.\n"
keywords = ""
locks = []
key = -1
to_room = 0
[rooms.7912.exits.north]
description = "You see the comfortable bedroom of Naris, the mansion of Redferne the Greater\nGod.\n"
keywords = "doors"
locks = ["ISDOOR", "CLOSED", "PICKPROOF"]
key = -1
to_room = 7911

[rooms.7913]
name = "怪物的監牢"
description = """
這個牢籠中似乎曾經關著一隻巨型的食肉動物。同時還被一條固定在牆上的
鎖鍊給拴著。這些景象讓你開始沒有安全感，雖然這裡沒有怪物的存在，但是你
還是可以感覺到你的手心正在冒汗。
"""
flags = ["UNDERGROUND", "NO_TELEPORT_IN"]
sector = "INSIDE"
[rooms.7913.exits.west]
description = "This looks like the only exit from here.\n"
keywords = "door cage metal pen"
locks = ["ISDOOR", "CLOSED", "PICKPROOF"]
key = -1
to_room = 7904

[rooms.7914]
name = "拱門石階"
description = """
一條相當長的石階，站在這裡你完全看不到階梯的盡頭，不知道還要多久才能抵達
樓梯的盡頭。好在一側的石牆上作有許多窗子透風，不至於太過悶熱，並且在向爬樓梯
的過程中也能一路欣賞住宅區的街景，讓人不會太無聊。
"""
flags = ["UNDERGROUND", "NO_TELEPORT_IN"]
sector = "INSIDE"
[rooms.7914.exits.down]
description = "走下樓梯可以回到拱門底部。\n"
keywords = ""
locks = []
key = -1
to_room = 3120
[rooms.7914.exits.up]
description = "一條長石階梯，不知道要多久才能走完。\n"
keywords = ""
locks = []
key = -1
to_room = 7915

[rooms.7915]
name = "拱門石階"
description = """
雖然依然看不見階梯的盡頭，但你相信自己已經爬完一半以上的樓梯。畢竟窗外的
視野在不知不覺中變成已經能夠看見人來人往的幻世大街了。如果這樣還不只有樓梯的
一半長，那這座拱門到底會有多高呢？也許再努力一下就能解答你的疑問了。
"""
flags = ["UNDERGROUND", "NO_TELEPORT_IN"]
sector = "INSIDE"
[rooms.7915.exits.down]
description = "走下樓梯可以回到拱門底部...不，也許用滾的會比較清鬆...\n"
keywords = ""
locks = []
key = -1
to_room = 7914
[rooms.7915.exits.up]
description = "一條長石階梯，不知道要多久才能走完。\n"
keywords = ""
locks = []
key = -1
to_room = 7916

[rooms.7916]
name = "石階的盡頭"
description = """
長時間的持續爬著階梯讓你感到非常疲憊，連高處的風景都懶得去看了。在你快要
累倒時，終於看到階梯的頂端連接著出口，只要走出去就能脫離這段爬樓梯的地獄了！
"""
flags = ["UNDERGROUND", "NO_TELEPORT_IN"]
sector = "INSIDE"
[rooms.7916.exits.down]
description = "一路滾下樓梯就可以回到拱門底部了。\n"
keywords = ""
locks = []
key = -1
to_room = 7915
[rooms.7916.exits.up]
description = "樓梯盡頭有一個出口。\n"
keywords = ""
locks = []
key = -1
to_room = 7900
