[area]
name = "{ 幫會} 伊謝爾倫要塞"
identity = "Zener"
builders = "伊謝爾倫要塞"
translator = "Zener"
modifier = "None"
vnum_start = 100251
vnum_end = 100300
security = 1
recall = 3001
f_toggle = true

[mobiles.100251]
keywords = "zener-cn"
short_description = "吉娜(Zener)"
long_description = "幫主吉娜(Zener)正在這裡為你祈福\n"
description = ""
act_flags = ["NPC", "SENTINEL", "STAY_AREA"]
affected_flags = []
alignment = 0
level = 40
mod_hitplus = 0
mod_mana = 0
mod_hitroll = 0
mod_damroll = 0
mod_ac = 0
mod_svs = 0
dodge = 0
mod_pp = 0
gold = 0
sex = "male"
race = "Halfling"
class = ["MAGE"]
special_function = "spec_cast_adept"

[mobiles.100252]
keywords = "tnt-cn"
short_description = "艦隊司令(Tnt)"
long_description = "艦隊總司令(Tnt)正在這裡指揮一切\n"
description = ""
act_flags = ["NPC", "SENTINEL", "STAY_AREA"]
affected_flags = []
alignment = 1000
level = 37
mod_hitplus = 0
mod_mana = 0
mod_hitroll = 0
mod_damroll = 0
mod_ac = 0
mod_svs = 0
dodge = 0
mod_pp = 0
gold = 0
sex = "male"
race = "Hobbit"

[mobiles.100253]
keywords = "no name"
short_description = "(no short description)"
long_description = "(no long description)\n"
description = ""
act_flags = ["NPC", "SENTINEL", "STAY_AREA"]
affected_flags = []
alignment = 0
level = 4
mod_hitplus = 0
mod_mana = 0
mod_hitroll = 0
mod_damroll = 0
mod_ac = 0
mod_svs = 0
dodge = 0
mod_pp = 0
gold = 0
sex = "neutral"

[mobiles.100254]
keywords = "no name"
short_description = "(no short description)"
long_description = "(no long description)\n"
description = ""
act_flags = ["NPC", "SENTINEL", "STAY_AREA"]
affected_flags = []
alignment = 0
level = 1
mod_hitplus = 0
mod_mana = 0
mod_hitroll = 0
mod_damroll = 0
mod_ac = 0
mod_svs = 0
dodge = 0
mod_pp = 0
gold = 0
sex = "neutral"

[mobiles.100255]
keywords = "oleum-cn"
short_description = "親切的貍貓老闆(oleum)"
long_description = "一位親切的貍貓老闆(oleum)正在這為你服務\n"
description = ""
act_flags = ["NPC", "SENTINEL", "STAY_AREA"]
affected_flags = []
alignment = 0
level = 38
mod_hitplus = 0
mod_mana = 0
mod_hitroll = 0
mod_damroll = 0
mod_ac = 0
mod_svs = 0
dodge = 0
mod_pp = 0
gold = 0
sex = "male"
race = "Vampire"

[mobiles.100256]
keywords = "Gylonochte-cn"
short_description = "羊威力(Gylonochte)"
long_description = "羊威力(Gylonochte)正坐在這裡喝酒聊天\n"
description = ""
act_flags = ["NPC", "SENTINEL", "STAY_AREA"]
affected_flags = []
alignment = 1000
level = 37
mod_hitplus = 0
mod_mana = 0
mod_hitroll = 0
mod_damroll = 0
mod_ac = 0
mod_svs = 0
dodge = 0
mod_pp = 0
gold = 0
sex = "male"
race = "Orc"

[mobiles.100257]
keywords = "no name"
short_description = "(no short description)"
long_description = "(no long description)\n"
description = ""
act_flags = ["NPC", "SENTINEL", "STAY_AREA"]
affected_flags = []
alignment = 0
level = 2
mod_hitplus = 0
mod_mana = 0
mod_hitroll = 0
mod_damroll = 0
mod_ac = 0
mod_svs = 0
dodge = 0
mod_pp = 0
gold = 0
sex = "neutral"

[objects.100251]
keywords = "wrd's slash"
short_description = "\u001B[37m伊謝爾倫要塞-\u001B[31m戰神之劍\u001B[37m(wrd's slash)\u001B[0m"
long_description = "伊謝爾倫要塞副司令之配劍"
action_description = ""
item_type = "WEAPON"
extra_flags = ["GLOW", "HUM", "DARK", "EVIL", "CLAN"]
wear_flags = ["TAKE", "WIELD"]
values = ["500", "0", "0", "11"]
weight = 70
cost = 1
level_limited = 0
level = 36
[[objects.100251.extra_descriptions]]
keywords = "伊謝爾倫要塞武器之首"
description = """
h
nw
"""

[objects.100252]
keywords = "Rose's thorn"
short_description = "玫瑰之棘(Rose's thorn)"
long_description = "一把雕飾著\u001B[31m玫瑰\u001B[0m花紋的匕首(dagger)"
action_description = ""
item_type = "WEAPON"
extra_flags = ["GLOW", "HUM", "DARK", "CLAN"]
wear_flags = ["TAKE", "WIELD"]
values = ["500", "0", "0", "11"]
weight = 20
cost = 1
level_limited = 0
level = 36

[objects.100253]
keywords = "water"
short_description = "一座噴水池(fountain)在這裡噴著水(water)."
long_description = "一座小噴泉(fountain)在這裡噴著水(water)."
action_description = ""
item_type = "FOUNTAIN"
extra_flags = ["CLAN"]
wear_flags = []
values = ["0", "0", "0", "0"]
weight = 1000
cost = 1036100
level_limited = 0
level = 36

[objects.100254]
keywords = "ccm's sword"
short_description = "\u001B[36m艦隊司令\u001B[37m西洋配劍\u001B[0m(ccm's sword)"
long_description = "一把細長的\u001B[37m西式長劍\u001B[0m(sword)"
action_description = ""
item_type = "WEAPON"
extra_flags = ["GLOW", "HUM", "DARK", "EVIL", "CLAN"]
wear_flags = ["TAKE", "WIELD"]
values = ["500", "0", "0", "11"]
weight = 20
cost = 1
level_limited = 0
level = 36

[objects.100255]
keywords = "grass"
short_description = "生日快樂羊"
long_description = "羊羊生日紀念船"
action_description = ""
item_type = "BOAT"
extra_flags = ["CLAN"]
wear_flags = ["TAKE"]
values = ["0", "0", "0", "0"]
weight = 10
cost = 0
level_limited = 0

[rooms.100251]
name = "伊謝爾倫自由廣場"
description = """
一陣閃光之後，你來到自由廣場，這裡是伊謝爾倫生活區的中心，所有的商業活動
都在這四周進行。此起彼落的喧嘩聲讓你瞭解了伊謝爾倫的活力，廣場的附近是一些熱
鬧的店家，你心想要在這裡找到屬意的物品，一定不是件難事。隱約由南面傳來酒杯碰
撞的聲音，引起了你的注意力，或許該去看看什麼地方會這麼地熱鬧。
"""
flags = ["NO_MOB", "UNDERGROUND"]
sector = "CITY"
[rooms.100251.exits.down]
description = ""
keywords = ""
locks = ["ISDOOR", "CLOSED"]
key = 0
to_room = 100268
[rooms.100251.exits.east]
description = ""
keywords = ""
locks = []
key = 0
to_room = 100255
[rooms.100251.exits.north]
description = ""
keywords = ""
locks = []
key = 0
to_room = 100254
[rooms.100251.exits.south]
description = ""
keywords = ""
locks = []
key = 0
to_room = 100252
[rooms.100251.exits.up]
description = ""
keywords = ""
locks = []
key = 0
to_room = 100256
[rooms.100251.exits.west]
description = ""
keywords = ""
locks = []
key = 0
to_room = 100253
[[rooms.100251.resets.mobiles]]
vnum = 100251
limit = 1
[[rooms.100251.resets.objects]]
vnum = 100253

[rooms.100252]
name = "自由廣場的南側"
description = ""
flags = ["UNDERGROUND"]
sector = "INSIDE"
[rooms.100252.exits.north]
description = ""
keywords = ""
locks = []
key = 0
to_room = 100251
[rooms.100252.exits.south]
description = ""
keywords = ""
locks = []
key = 0
to_room = 100257

[rooms.100253]
name = "自由廣場的西側"
description = """
這裡是自由廣場西側，除了相同的熱鬧嘈雜的聲音外，西邊似乎傳來了打造東西的聲音。
"""
flags = ["UNDERGROUND"]
sector = "INSIDE"
[rooms.100253.exits.east]
description = ""
keywords = ""
locks = []
key = 0
to_room = 100251
[rooms.100253.exits.west]
description = ""
keywords = ""
locks = ["ISDOOR", "CLOSED"]
key = 0
to_room = 100267

[rooms.100254]
name = "自由廣場的北側"
description = ""
flags = ["UNDERGROUND"]
sector = "INSIDE"
[rooms.100254.exits.north]
description = ""
keywords = ""
locks = []
key = 0
to_room = 100265
[rooms.100254.exits.south]
description = ""
keywords = ""
locks = []
key = 0
to_room = 100251

[rooms.100255]
name = "自由廣場的東側"
description = ""
flags = ["UNDERGROUND"]
sector = "INSIDE"
[rooms.100255.exits.west]
description = ""
keywords = ""
locks = []
key = 0
to_room = 100251

[rooms.100256]
name = "控制臺"
description = """
這裡是要塞的中樞地帶，往南是星艦的會議室，往北是星艦的作戰指揮中心，
往上是星艦司令所在的房間，兩旁可以通往星艦的個人休息室，專門供給星艦成員
休息的地方。你也可以往下回到自由廣場。
"""
flags = ["UNDERGROUND"]
sector = "INSIDE"
[rooms.100256.exits.down]
description = ""
keywords = ""
locks = []
key = 0
to_room = 100251
[rooms.100256.exits.east]
description = ""
keywords = ""
locks = []
key = 0
to_room = 100262
[rooms.100256.exits.north]
description = ""
keywords = ""
locks = []
key = 0
to_room = 100258
[rooms.100256.exits.south]
description = ""
keywords = ""
locks = ["ISDOOR"]
key = 0
to_room = 100259
[rooms.100256.exits.up]
description = ""
keywords = ""
locks = []
key = 0
to_room = 100264
[rooms.100256.exits.west]
description = ""
keywords = ""
locks = []
key = 0
to_room = 100260

[rooms.100257]
name = "自由鬥士酒吧"
description = """
走進這裡，耳邊傳來陣陣交談和酒杯碰撞聲，不少旅者在這休息也趁機交換著一路旅行
的心得。眼前有個寬闊的吧檯，親切的貍貓老闆正在這為你服務，既然來了就不醉不歸吧。
"""
flags = ["UNDERGROUND", "AUCTION"]
sector = "INSIDE"
[rooms.100257.exits.north]
description = ""
keywords = ""
locks = []
key = 0
to_room = 100252
[[rooms.100257.resets.mobiles]]
vnum = 100255
limit = 1
[[rooms.100257.resets.mobiles]]
vnum = 100256
limit = 1

[rooms.100258]
name = "控制中心"
description = ""
flags = ["UNDERGROUND"]
sector = "INSIDE"
[rooms.100258.exits.south]
description = ""
keywords = ""
locks = []
key = 0
to_room = 100256

[rooms.100259]
name = "會議室"
description = ""
flags = ["UNDERGROUND"]
sector = "INSIDE"
[rooms.100259.exits.north]
description = "一扇木製的雕花大門(wooden door)\n"
keywords = "wooden door"
locks = ["ISDOOR"]
key = 0
to_room = 100256

[rooms.100260]
name = "西之迴廊"
description = ""
flags = ["UNDERGROUND"]
sector = "INSIDE"
[rooms.100260.exits.east]
description = ""
keywords = ""
locks = []
key = 0
to_room = 100256
[rooms.100260.exits.north]
description = ""
keywords = ""
locks = []
key = 0
to_room = 100261
[rooms.100260.exits.south]
description = ""
keywords = ""
locks = []
key = 0
to_room = 100272

[rooms.100261]
name = "要塞副司令之間"
description = ""
flags = ["UNDERGROUND"]
sector = "INSIDE"
[rooms.100261.exits.south]
description = ""
keywords = ""
locks = []
key = 0
to_room = 100260

[rooms.100262]
name = "東之迴廊"
description = ""
flags = ["UNDERGROUND"]
sector = "INSIDE"
[rooms.100262.exits.north]
description = ""
keywords = ""
locks = []
key = 0
to_room = 100263
[rooms.100262.exits.west]
description = ""
keywords = ""
locks = []
key = 0
to_room = 100256

[rooms.100263]
name = "艦隊司令之間"
description = ""
flags = ["UNDERGROUND"]
sector = "INSIDE"
[rooms.100263.exits.south]
description = ""
keywords = ""
locks = []
key = 0
to_room = 100262

[rooms.100264]
name = "要塞總司令之間"
description = ""
flags = ["UNDERGROUND"]
sector = "INSIDE"
[rooms.100264.exits.down]
description = ""
keywords = ""
locks = []
key = 0
to_room = 100256
[[rooms.100264.resets.mobiles]]
vnum = 100252
limit = 1

[rooms.100265]
name = "陣亡將士紀念館"
description = """
在此向為了自己所堅持的理念而犧牲了生命
致上最深的敬意。
陣亡將士 <lv 5> 席娜     Zener
         <lv 4> 可可姆   Ccm
         <lv 3> 魔精兔   Defiler
         <lv ?> 小哈     Sheauha
         <lv 3> 貍貓太子 Oleum
         <lv 3> 羊威力   Gylonochte
"""
flags = ["UNDERGROUND"]
sector = "INSIDE"
[rooms.100265.exits.down]
description = ""
keywords = ""
locks = ["ISDOOR", "CLOSED"]
key = 0
to_room = 100266
[rooms.100265.exits.south]
description = ""
keywords = ""
locks = []
key = 0
to_room = 100254

[rooms.100266]
name = "某處"
description = """
這裡是?
有如月球表面般冰冷。
究竟有些什麼？

你回頭一望！

一具冰冷的太空艙躺在這裡。
"""
flags = ["UNDERGROUND"]
sector = "INSIDE"
[rooms.100266.exits.up]
description = ""
keywords = ""
locks = ["ISDOOR", "CLOSED"]
key = 0
to_room = 100265

[rooms.100267]
name = "鑄造場"
description = ""
flags = ["NO_MOB", "UNDERGROUND"]
sector = "INSIDE"
[rooms.100267.exits.east]
description = ""
keywords = ""
locks = ["ISDOOR", "CLOSED"]
key = 0
to_room = 100253

[rooms.100268]
name = "競技場"
description = ""
flags = ["PK"]
sector = "INSIDE"
[rooms.100268.exits.up]
description = ""
keywords = ""
locks = ["ISDOOR", "CLOSED"]
key = 0
to_room = 100251

[rooms.100269]
name = "莽。刻之館"
description = """
這裡是羊威力(Gylonochte)休息室，你可以看到有三隻羊正在這悠閒地吃草
"""
flags = ["NO_MOB", "UNDERGROUND", "NO_TELEPORT_IN"]
sector = "INSIDE"
[rooms.100269.exits.west]
description = ""
keywords = ""
locks = ["ISDOOR", "CLOSED"]
key = 0
to_room = 100272

[rooms.100270]
name = ""
description = """
這裡是小哈(sheauha)休息室
"""
flags = ["NO_MOB", "UNDERGROUND", "NO_TELEPORT_IN"]
sector = "INSIDE"

[rooms.100271]
name = "core休息室"
description = ""
flags = ["NO_MOB", "UNDERGROUND"]
sector = "INSIDE"

[rooms.100272]
name = "休息室走道"
description = """
這裡是通往每個人房間的走道
"""
flags = ["UNDERGROUND"]
sector = "INSIDE"
[rooms.100272.exits.east]
description = "202號房\n"
keywords = "Gylonochte房間"
locks = ["ISDOOR", "CLOSED"]
key = 0
to_room = 100269
[rooms.100272.exits.north]
description = ""
keywords = ""
locks = []
key = 0
to_room = 100260
[rooms.100272.exits.south]
description = ""
keywords = ""
locks = []
key = 0
to_room = 100274
[rooms.100272.exits.west]
description = "201號房\n"
keywords = "oleum房間"
locks = ["ISDOOR", "CLOSED"]
key = 0
to_room = 100273

[rooms.100273]
name = "Oleum休息室"
description = ""
flags = ["UNDERGROUND"]
sector = "INSIDE"
[rooms.100273.exits.east]
description = ""
keywords = ""
locks = ["ISDOOR", "CLOSED"]
key = 0
to_room = 100272

[rooms.100274]
name = "休息室走道"
description = """
這裡是通往每個人房間的走道
"""
flags = ["UNDERGROUND"]
sector = "INSIDE"
[rooms.100274.exits.east]
description = "204號房\n"
keywords = "Matt休息室"
locks = ["ISDOOR", "CLOSED"]
key = 0
to_room = 100275
[rooms.100274.exits.north]
description = ""
keywords = ""
locks = []
key = 0
to_room = 100272
[rooms.100274.exits.west]
description = "203號房\n"
keywords = "basha房間"
locks = ["ISDOOR", "CLOSED"]
key = 0
to_room = 100276

[rooms.100275]
name = "Matt休息室"
description = """
這裡是Matt休息室
"""
flags = ["SAVE", "NO_TELEPORT_IN"]
sector = "INSIDE"
[rooms.100275.exits.west]
description = ""
keywords = ""
locks = ["ISDOOR", "CLOSED"]
key = 0
to_room = 100274

[rooms.100276]
name = "羅德館-芭夏休息室"
description = """
這裡是basha休息室
"""
flags = ["SAVE", "NO_TELEPORT_IN"]
sector = "INSIDE"
[rooms.100276.exits.east]
description = ""
keywords = ""
locks = ["ISDOOR", "CLOSED"]
key = 0
to_room = 100274
