#! /bin/sh
# Written by Furey.
# With additions from Tony.
# With changes from Kahn.
# Ported to 'sh' by Loki for those who don't have 'csh'.
# Thanks to Alan and Grodyn for thier help on the redirecting stuff - Loki

# Set the port number.
#if [ "$1" != "" ]
#then
#         port=$1 
#else
#         port=5555
#fi
port=5555

# Force use newest src. Keric
#make clean
#make update
#make install

# Change to area directory.
cd ../area
#make update

# Set limits. (cannot be used in a 'sh' script - Loki)
# nohup
# nice
# limit stack 1024k
if [ -r SHUTDOWN.TXT ]
then
	rm -f SHUTDOWN.TXT
fi
while [ 1 ]
do

	# If you want to have logs in a different directory,
	#   change the 'logfile=' line to reflect the directory name.
	# (It isn't used but I let it in anyway)
	#index=1000
	#exist=`ps -u mudadm -f | grep "envy2 5500"`
	#if [ "$exist" = "" ]
	#then
		#while [ 1 ]
		#do
		#	logfile=../log/$index.log
		#	if [ -r $logfile ]
		#	then
		#		# If you don't have bc you have a problem... :(
		#		index=`echo $index + 1|bc`
		#	else
		#		break
		#	fi
		#done
		# Update to new code if possible.
		#if [ -r ../src/envy.new ]
		#then
		#	\mv ../src/envy ../src/envy.old
		#	\mv ../src/envy.new ../src/envy
		#fi

		#if [ -r ../src/envy_logger.new ]
		#then
		#	\mv ../src/envy_logger ../src/envy_logger.old
		#	\mv ../src/envy_logger.new ../src/envy_logger
		#fi

		# Clear OLD unused player files
		#find ../player/? -type f -atime +400 -print -exec rm -f {} \; >> ../log/removed_players

		# gzip player files
		#gzip -fqr -9 ../player/?
		#gzip -fqr -9 ../player/backup/?

	echo 'run envy'
	# Run envy.
	# Thanks to Alan and Grodyn for their help on the redirecting stuff - Loki
	#../src/envy2 $port >$logfile 2>&1
	used=`../src/envy2 $port 2>&1`
	if [ "$used" = "Init_socket: bind: Address already in use" ]
	then
		echo 'Init_socket: bind: Address already in use'
		sleep 60
	else
		if [ -r core ]
		then
			\mv core ../src/
		fi
	fi
	#else
	#	echo $exist
	#fi

#  # Restart, giving old connections a chance to die.
#  if [ -r SHUTDOWN.TXT ]
#  then
#		    sleep 1
#  else
#        # rm -f SHUTDOWN.TXT
#        exit 0
#  fi
	sleep 15
done
