# Auto-converted from ansi.h
import typing

# ansi.h: Define constants for ANSI terminal escape codes used to color game text.
# ansi.h: 定義 ANSI 終端控制碼常數，用於對遊戲內的文字進行著色與格式化。
ESC = ""
BLK = ESC + "[30m"
RED = ESC + "[31m"
GRN = ESC + "[32m"
YEL = ESC + "[33m"
BLU = ESC + "[34m"
PUR = ESC + "[35m"
CYN = ESC + "[36m"
WHT = ESC + "[37m"
NOR = ESC + "[0m"
HIB = ESC + "[1;30m"
HIR = ESC + "[1;31m"
HIG = ESC + "[1;32m"
HIY = ESC + "[1;33m"
HIU = ESC + "[1;34m"
HIP = ESC + "[1;35m"
HIC = ESC + "[1;36m"
HIW = ESC + "[1;37m"
BBLK = ESC + "[40m"
BRED = ESC + "[41m"
BGRN = ESC + "[42m"
BYEL = ESC + "[43m"
BBLU = ESC + "[44m"
BPUR = ESC + "[45m"
BCYN = ESC + "[46m"
BWHT = ESC + "[47m"
BHIB = ESC + "[1;40m"
BHIR = ESC + "[1;41m"
BHIG = ESC + "[1;42m"
BHIY = ESC + "[1;43m"
BHIU = ESC + "[1;44m"
BHIP = ESC + "[1;45m"
BHIC = ESC + "[1;46m"
BHIW = ESC + "[1;47m"
HILIGHT = ESC + "[1m;"
BLINKING = ESC + "[5m;"